use_frameworks!

platform :ios, '9.0'

target 'JSONContentManager_Example' do
  pod 'JSONContentManager', :path => '../'

  target 'JSONContentManager_Tests' do
    inherit! :search_paths

    
  end
end
